spring:
  datasource:
    url: jdbc:h2:mem:currency-db
    driverClassName: org.h2.Driver
    username: user
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

riksbank:
  api:
    key: "d06a3e29b2664719a1b4c4ff03a2a607"
